### ISSUE TITLE
Knopflerfish fails to start if arbitraty working directory contains files with special names

### ISSUE THREAD

**Issue by dpolivaev** [knopflerfish/knopflerfish.org#11]
Usually SystemBundle.initSystemBundle() initializes list of packages exported by `SystemBundle` reading lists contained in internal resource files `packages.txt` and `exports` contained in `framework.jar` using internal method `addSysPackagesFromFile` . The same method is used to add packages from file given in property org.knopflerfish.framework.system.packages.file . Therefore this method tries to find the file on the disk before it takes the resource from the jar.

~~~
final File f = new File(new File(sysPkgFile).getAbsolutePath());

    if (!f.exists() || !f.isFile()) {
      url = SystemBundle.class.getResource(sysPkgFile);
      if (null == url) {
        url = SystemBundle.class.getResource("/" + sysPkgFile);
      }
~~~

Unfortunately it causes a failure if the working directory occasionally contains files with matching names. Our users have experienced such failures.

Therefore I ask you to change the above logic so that framework can be started in any directory and it does not depend on its content.

As a work around I am going to temporarily change values of system property `user.dir` when the framework is initialized and change it back when the first plug-in is being  activated.

**Comment by janste63** [comment]
Removed resource override from current working directory. Now we require explicit override. Fix available in framework 8.0.3. Download from https://bintray.com/knopflerfish/master/download_file?file_path=distrib_6.0.0.snapshot-1701041603-master%2Fknopflerfish_osgi_sdk_6.0.0.snapshot-1701041603-master.jar
