### ISSUE TITLE
NullPointerException - ResolverHooks.filterMatches()

### ISSUE THREAD

**Issue by janste63** [knopflerfish/knopflerfish.org#12]
At framework start, we’re occasionally seeing this NullPointerException in ResolverHooks.filterMatches()

**Comment by janste63** [comment]
This race condition due to missing synchronize around two synchronized methods.

**Comment by janste63** [comment]
Fixed in framework  version 7.2.5(KF5) and framework version 8.0.1(KF6). Download from https://bintray.com/knopflerfish/master/download_file?file_path=distrib_6.0.0.snapshot-1701031049-master%2Fknopflerfish_osgi_sdk_6.0.0.snapshot-1701031049-master.jar

**Comment by buzz3791** [comment]
@janste63 Is there a URL for the binary containing framework JAR version 7.2.5 (KF5)?
