### ISSUE TITLE
Patches for Debian package

### ISSUE THREAD

**Issue by fnatter** [knopflerfish/knopflerfish.org#25]
hello knopflerfish developers,

I am using this channel because unfortunately, no mailing list seems to exist
(http://www.knopflerfish.org/mailman/listinfo). Is there something I missed?

I have two simple questions concerning patching 6.1.0's framework's build system (osgi/framework/build.xml):

1. how can I build with another osgi.annotation jar? I tried this:
```
-  <property name="osgi.annotation.jar" location="${topdir}/annotations/osgi.annotation-6.0.1.jar"/>
+  <property name="osgi.annotation.jar" location="/usr/share/java/osgi.annotation.jar"/>
```
but I still get:
```
[javac]
/home/felix/knopflerfish-osgi-unstable/knopflerfish-osgi/osgi/framework/src/org/osgi/framework/Constants.java:19:
error: package org.osgi.annotation.versioning does not exist
```
```
$ jar tf /usr/share/java/osgi.annotation.jar
META-INF/
META-INF/MANIFEST.MF
org/
org/osgi/
org/osgi/annotation/
org/osgi/annotation/versioning/
org/osgi/annotation/versioning/ConsumerType.class
org/osgi/annotation/versioning/ProviderType.class
org/osgi/annotation/versioning/Version.class
org/osgi/annotation/versioning/package-info.class
```

2. How can I build without android support? Is the following patch correct?
```
-  <import file="${ant.dir}/android.xml"/>
+  <!--<import file="${ant.dir}/android.xml"/>-->
```

Many Thanks!
Felix

**Comment by janste63** [comment]
Hi Felix,

1) It should work fine to change the path to the annotation jar. Have you tried to replace the osgi.annotation-6.0.1.jar with your copy in the original build system?

2) Should work fine. You can also unset the ANDROID_HOME environment variable to disable android builds.

    /Jan

**Comment by fnatter** [comment]
hi Jan,

thanks for the quick reply. The property seems to be ignored, but your hint led me to
create a symlink of Debian's jar to where your build system expects it:
`ln -s /usr/share/java/osgi.annotation.jar osgi/annotations/osgi.annotation-6.0.1.jar`
This works fine, thanks!

**Comment by janste63** [comment]
Great that you found a solution. The reason for the property seemingly being ignored is that the jar is referred in several locations (ant/bundlebuild.xml, ant/bundletasks.xml, osgi/build.xml and osgi/framework/build.xml). So depending on how and what you build, these different definitions will be used).
