### ISSUE TITLE
Knopflerfish Maven Repo is not available for the latest release

### ISSUE THREAD

**Issue by dpolivaev** [knopflerfish/knopflerfish.org#6]
http://www.knopflerfish.org/maven2/ and particularly 
http://www.knopflerfish.org/releases/6.0.0/maven2/org/knopflerfish/framework/
return status 404

**Comment by chlarsson** [comment]
Hi, 
you can find all artifacts at:
http://www.knopflerfish.org/releases/6.0.0/maven2/org/knopflerfish/KF-6.0.0_dependencyManagement.xml

This link should be more clearly advertised. 

Unfortunately directory listing is not supported on git hub pages. This is why you get the 404 error code. 

Regards,
Christer

**Comment by dpolivaev** [comment]
The actual reason for the issue is that the following configuration did not work:

```
configure(subprojects.findAll {it.name =~ /plugin/ || it.name =~ /^freeplane$/ || it.name =~ /^freeplane_framework$/}){
    repositories {
        maven {
            url 'http://www.knopflerfish.org/maven2/'
        }
    }

    dependencies {
        compile group: 'org.knopflerfish', name:'framework', version: '8.0.0'
    }
}
```

**Comment by chlarsson** [comment]
At the moment you'll have to set it to:
'http://www.knopflerfish.org/releases/6.0.0/maven2/'

**Comment by dpolivaev** [comment]
Finally I have set it to 'https://dl.bintray.com/knopflerfish/knopflerfish-maven/' and it seems to work

**Comment by dpishchukhin** [comment]
any reason to avoid maven central for the artifacts?

**Comment by dpolivaev** [comment]
I think it is not available there yet. http://search.maven.org/#search%7Cga%7C1%7Cknopflerfish returns no result-

**Comment by dpishchukhin** [comment]
are there any plans to publish artifacts to maven central?

**Comment by chlarsson** [comment]
Yes there are. A problem or issue we are facing with maven is that we only change bundle versions when the actual source code is changed. In Knopflerfish we use a source code version first approach, where a KF distribution can be compiled for different JDK versions. So for a bundle that hasn't changed between KF4, KF5 and KF6 the bundle version is the same, but potentially compiled for different JDK versions. This is not a problem for the self-contained Knopflerfish distributions, but does not play well with one centralized maven repository.

We are looking into different solutions:
1. Use different group id's for every main release of Knopflerfish
2. Add the KF main release to the artifact id, e.g. framework-kf6-8.0.0
3. Use a version qualifier to mark the main version of KF
4. Use a maven classifier

Feedback on which solution would be best is most welcome!

**Comment by dpolivaev** [comment]
From my point the issue is closed. I am satisfied with the bintray repository.

**Comment by dpishchukhin** [comment]
All Maven central discussions moved to #9
